### ISSUE TITLE
SchemaModel.cast doesn't work properly

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/jsontableschema-py#39]
I've been trying this package to integrate with https://github.com/okfn/datapackage-py but had a few issues. This is my test file:

```python
from jsontableschema.model import SchemaModel

resource_schema = {
    "fields": [
        {
            "name": "Country Name",
            "type": "string"
        },
        {
            "name": "Country Code",
            "type": "string",
            "foreignkey": "iso-3-geo-codes/id"
        },
        {
            "name": "Year",
            "type": "date",
            "format": "yyyy"
        },
        {
            "name": "Value",
            "description": "GDP in current USD",
            "type": "number"
        }
    ]
}
schema = SchemaModel(resource_schema)

schema.required_headers
# [u'Country Name', u'Country Code', u'Year', u'Value']

country_name = schema.cast('Country Name', 'Brazil')  # jsontableschema.exceptions.InvalidCastError: Could not cast value
country_code = schema.cast('Country Code', 'BRA')     # jsontableschema.exceptions.InvalidCastError: Could not cast value
year = schema.cast('Year', '2015')                    # jsontableschema.exceptions.InvalidDateType: time data '2015' does not match format '%Y-%m-%d'
gdp = schema.cast('Value', '123.45')                  # OK
```

The schema comes from https://github.com/datasets/gdp.

**Comment by pwalsh** [comment]
@vitorbaptista casting recently changed. I'm not available for a few days, but please check with @brew on this.

**Comment by roll** [comment]
@vitorbaptista 
Is it still actual?

**Comment by roll** [comment]
CLOSED

Please re-open if it's still an actual issue.

**Comment by vitorbaptista** [comment]
@roll I'm not sure if the API is still the same, but I've ran the same code I've posted on the first comment in this issue and the result is the same except for `schema.required_headers` that return `[]`.

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jsontableschema.model import SchemaModel
>>> resource_schema = {
...     "fields": [
...         {
...             "name": "Country Name",
...             "type": "string"
...         },
...         {
...             "name": "Country Code",
...             "type": "string",
...             "foreignkey": "iso-3-geo-codes/id"
...         },
...         {
...             "name": "Year",
...             "type": "date",
...             "format": "yyyy"
...         },
...         {
...             "name": "Value",
...             "description": "GDP in current USD",
...             "type": "number"
...         }
...     ]
... }
>>> schema = SchemaModel(resource_schema)
>>> schema.required_headers
[]
>>> country_name = schema.cast('Country Name', 'Brazil')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jsontableschema/model.py", line 97, in cast
    return _type.cast(value)
  File "jsontableschema/types.py", line 101, in cast
    cast_value = getattr(self, _handler)(value)
  File "jsontableschema/types.py", line 133, in cast_default
    raise exceptions.InvalidCastError('Could not cast value')
jsontableschema.exceptions.InvalidCastError: Could not cast value
>>> country_code = schema.cast('Country Code', 'BRA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jsontableschema/model.py", line 97, in cast
    return _type.cast(value)
  File "jsontableschema/types.py", line 101, in cast
    cast_value = getattr(self, _handler)(value)
  File "jsontableschema/types.py", line 133, in cast_default
    raise exceptions.InvalidCastError('Could not cast value')
jsontableschema.exceptions.InvalidCastError: Could not cast value
>>> year = schema.cast('Year', '2015')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jsontableschema/model.py", line 97, in cast
    return _type.cast(value)
  File "jsontableschema/types.py", line 103, in cast
    cast_value = self.cast_default(value)
  File "jsontableschema/types.py", line 325, in cast_default
    raise_with_traceback(exceptions.InvalidDateType(e))
  File "jsontableschema/types.py", line 323, in cast_default
    return datetime.datetime.strptime(value, self.ISO8601).date()
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
jsontableschema.exceptions.InvalidDateType: time data '2015' does not match format '%Y-%m-%d'
>>> gdp = schema.cast('Value', '123.45')
>>>
```

**Comment by roll** [comment]
FIXED

https://github.com/frictionlessdata/jsontableschema-py/pull/56

---

About date format error - following the latest spec it should be:
```
        {
            "name": "Year",
            "type": "date",
            "format": "fmt:%Y"
        }
```
